name: build_r_dependencies
on: [push]
jobs:
  initial-setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Job is now running on a ${{ runner.os }} server hosted by GitHub"
      - run: echo "Name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository has been cloned to the runner."
      - run: echo "️Workflow now ready to test code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        R: [ '4.0.0', '4.1.0' , '4.2.0' ]
    name: R ${{ matrix.R }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
      - run: Rscript -e 'print("hello")'
