name: build_r_dependencies
on: [push]
jobs:
  matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04]
#        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-10.15, macos-11, macos-12]
#        R: [ '3.6.3', '4.0.0', '4.1.0' , '4.2.0' ]
        R: [ '4.2.0' ]
    name: R ${{ matrix.R }} on ${{ matrix.os }}
    steps:
      - name: Setup R
        - uses: actions/checkout@v2
        - uses: r-lib/actions/setup-r@v2
        - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          r-version: ${{ matrix.R }}
      - run: Rscript -e 'print("hello")'
    runs-on: ${{ matrix.os }}
