name: build_r_dependencies
on: [push]
jobs:
  matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04]
#        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-10.15, macos-11, macos-12]
#        R: [ '3.6.3', '4.0.0', '4.1.0' , '4.2.0' ]
        R: [ '4.2.0' ]
    steps:
    name: R ${{ matrix.R }} on ${{ matrix.os }}
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 1
        extra-packages: |
          any::ggplot2
          any::rcmdcheck
        needs: |
          website
          coverage
    - run: Rscript -e 'library(biomaRt)'

    name: R ${{ matrix.R }} on ${{ matrix.os }} 2
    - run: Rscript -e 'SessionInfo()


    runs-on: ${{ matrix.os }}

    ### todo: get devtools / circtest installed
    ### via run in extra command
    # make sure cache works
   # run sample circtools call?

#    steps:
#      - uses: actions/checkout@v2
#      - uses: r-lib/actions/setup-r@v2
#        uses: r-lib/actions/setup-r-dependencies@v2
#      - name: Setup R
#        with:
#          r-version: ${{ matrix.R }}
#      - run: Rscript -e 'print("hello")'
#    runs-on: ${{ matrix.os }}
