name: build_r_dependencies
on: [push]
jobs:
  matrix:
    strategy:
      matrix:
        os: [ubuntu-22.04]
#        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-10.15, macos-11, macos-12]
#        R: [ '3.6.3', '4.0.0', '4.1.0' , '4.2.0' ]
        R: [ '4.2.0' ]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
    - name: Set up R ${{ matrix.R }} on ${{ matrix.os }}
      with:
        cache-version: 1
    - run: Rscript -e 'library(biomaRt)'

    # python now
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Set up Python ${{ matrix.python-version }}
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    runs-on: ${{ matrix.os }}

    ## todo: get devtools / circtest installed
    ### via run in extra command
    # make sure cache works
   # run sample circtools call?

#    steps:
#      - uses: actions/checkout@v2
#      - uses: r-lib/actions/setup-r@v2
#        uses: r-lib/actions/setup-r-dependencies@v2
#      - name: Setup R
#        with:
#          r-version: ${{ matrix.R }}
#      - run: Rscript -e 'print("hello")'
#    runs-on: ${{ matrix.os }}
