jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        R: [ '4.2.0' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          cache-version: 1
      - run: Rscript -e 'SessionInfo()'
