name: Set up R environment
on: [push]
jobs:
  job1:
    strategy:
      matrix:
        os: [ubuntu-22.04]
#        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-10.15, macos-11, macos-12]
#        R: [ '3.6.3', '4.0.0', '4.1.0' , '4.2.0' ]
        R: [ '4.2.0' ]
        # python-version: ["3.7", "3.8", "3.9", "3.10"]
    name: R ${{ matrix.R }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 1
        extra-packages: |
          github::dieterich-lab/CircTest
          github::dieterich-lab/primex
    - run: Rscript -e 'library(primex)'
    runs-on: ${{ matrix.os }}

  job2:
    strategy:
      matrix:
        os: [ubuntu-22.04]
#        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, macos-10.15, macos-11, macos-12]
#        R: [ '3.6.3', '4.0.0', '4.1.0' , '4.2.0' ]
        #R: [ '4.2.0' ]
        # python-version: ["3.7", "3.8", "3.9", "3.10"]
        python-version: ["3.8"]
    name: Python ${{ matrix.version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
        python-version: ${{ matrix.python-version }}
    - run: |
        python -m pip install --upgrade pip
        python -m pip install circtools
        circtools --version
    runs-on: ${{ matrix.os }}
